In [35]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [37]:
dataset = pd.read_csv('datamining.csv', sep=";")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


In [39]:
print (x)

[['France' nan 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' 52.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [41]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [45]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer (missing_values=np.nan, strategy='mean') 
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])


NameError: name 'X' is not defined

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct =ColumnTransformer (transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [20]:
print(x)

[[1.0 0.0 0.0 nan 72000]
 [0.0 0.0 1.0 27.0 48000]
 [0.0 1.0 0.0 30.0 54000]
 [0.0 0.0 1.0 38.0 61000]
 [0.0 1.0 0.0 40.0 0]
 [1.0 0.0 0.0 35.0 58000]
 [0.0 0.0 1.0 52.0 52000]
 [1.0 0.0 0.0 48.0 79000]
 [0.0 1.0 0.0 50.0 83000]
 [1.0 0.0 0.0 37.0 67000]]


In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)


In [25]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [27]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)


In [29]:
print(x_train)

[[0.0 0.0 1.0 52.0 52000]
 [0.0 1.0 0.0 40.0 0]
 [1.0 0.0 0.0 nan 72000]
 [0.0 0.0 1.0 38.0 61000]
 [0.0 0.0 1.0 27.0 48000]
 [1.0 0.0 0.0 48.0 79000]
 [0.0 1.0 0.0 50.0 83000]
 [1.0 0.0 0.0 35.0 58000]]


In [31]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000]
 [1.0 0.0 0.0 37.0 67000]]
